services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Wexample\SymfonyTranslationsDemo\Controller\:
        resource: '../../Controller/'
        tags: ['controller.service_arguments']

    Wexample\SymfonyTranslationsDemo\Repository\:
        resource: '../../Repository/'
